Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,7 +34,7 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install scholarly requests beautifulsoup4 || { echo "Installation failed"; exit 1; }
+        pip install scholarly>=1.7.11 requests beautifulsoup4 || { echo "Installation failed"; exit 1; }
 
     - name: Run citation update script
       run: python update_citation_matrix.py
